#!/bin/bash

icon() {
        # not connected
        if [ $(bluetoothctl show | grep "Powered: yes" | wc -c) -eq 0 ]; then
                #     echo $HOME/.local/icons/bluetooth-off.svg
                echo "󰂲"
        else
                # connected, but no device
                if [ $(bluetoothctl info | grep 'Device' | wc -c) -eq 0 ]; then
                        #     echo $HOME/.local/icons/bluetooth-on.svg
                        echo "󰂯"
                else
                        # get device alias
                        #    DEVICE=`echo info | bluetoothctl | grep 'Alias:' | awk -F:  '{ print $2 }'`
                        #    BATTERY=`upower -i /org/freedesktop/UPower/devices/headset_dev_33_33_55_33_90_D0 | grep percentage | cut -b 26-28`
                        echo "󰂱"
                fi
        fi
}

state() {
        # not connected
        if [ $(bluetoothctl show | grep "Powered: yes" | wc -c) -eq 0 ]; then
                echo "Disconnected"
        else
                # connected, but no device
                if [ $(echo info | bluetoothctl | grep 'Device' | wc -c) -eq 0 ]; then
                        echo "Connected"
                else
                        # get device alias
						DEVICE="$(bluetoothctl info | grep 'Alias:' | awk -F:  '{ print $2 }')"
						BATTERY="$(bluetoothctl info | tail -1 | sed -n 's/.*(\([0-9]\+\)).*/\1/p')"
						if [ -z "$DEVICE" ]; then 
							echo "No Devices"
						else
							echo "$DEVICE $BATTERY%"
						fi

                fi
        fi
}
toggle() {
	if [ $(bluetoothctl show | grep PowerState\: | awk '{print $2}') == "on" ]; then 
		bluetoothctl power off 
	else 
		bluetoothctl power on 
	fi
}
	
if [[ $1 == "--toggle" ]]; then
		toggle
	else
		echo "[\"$(state)\",\"$(icon)\"]"
fi
