#!/bin/ruby 

require 'open-uri'
require 'json'

def get_data  
  city = ""
  key = ""
  path = "/tmp"
  #url = "http://api.openweathermap.org/data/2.5/weather?q=#{city}&appid=#{key}&units=metric"
  begin 
    json = URI.open("http://api.openweathermap.org/data/2.5/weather?q=#{city}&appid=#{key}&units=metric").read
    #html = URI.open(url)
  rescue => e
    puts "Error: #{e.message}"
  end

  data = JSON.parse(json)

  main = data['weather'][0]['description']
  icon = data['weather'][0]['icon']
  temp = data['main']['temp'].round(1)
  temp = temp.to_s + "℃ "

  case icon
  when "01d"
   icon=" "
  when "01n"
    icon=" "
  when "02d"
    icon=" "
  when "02n"
    icon=" "
  when "03d"
    icon=" "
  when "03n"
    icon=" "
  when "04d"
    icon=" "
  when "04n"
    icon=" "
  when "09d"
    icon=" "
  when "09n"
    icon=" "
  when "10d"
    icon=" "
  when "10n"
    icon=" "
  when "11d"
    icon=""
  when "11n"
    icon=""
  when "13d"
    icon=" "
  when "13n"
    icon=" "
  when "50d"
    icon=" "
  when "50n"
    icon=" "
  else 
    icon=" "
  end

  print '["',main,'","',temp,'","',icon,'"]'
  unless File.directory?(path)
    Dir.mkdir(path)
  end

  file_main = open(path+'/weather',"w") do |f|
    f.write("[\"#{main}\",\"#{temp}\",\"#{icon}\"]")
  end
end
def get_time
  path = "/tmp/weather"
  if File.exist?(path)
    modifytime = File.stat(path).mtime 
    time_diff = Time.now - modifytime 
    if time_diff >= 900
      get_data()
    else 
      cache = open(path,"r").read 
      puts cache
    end 
  else 
    get_data()
  end 
end

get_time()
