#!/bin/bash


## Get Battery 
get_percentage() {
    BAT=$(ls /sys/class/power_supply | grep BAT | head -n 1)
    echo "$(cat /sys/class/power_supply/${BAT}/capacity)%"
}

## Get Battery Icon
get_icon() {
    BAT=$(ls /sys/class/power_supply | grep BAT | head -n 1)
    BATSTATUS="$(cat /sys/class/power_supply/${BAT}/status)"
    BATVAL="$(cat /sys/class/power_supply/${BAT}/capacity)"

    if [[ "$BATSTATUS" == "Discharging" ]];then
      if [ "$BATVAL" -gt 75 ] && [ "$BATVAL" -le 101 ];then
        echo ""
      elif [ "$BATVAL" -gt 50 ] && [ "$BATVAL" -le 75 ];then
        echo ""
      elif [ "$BATVAL" -gt 25 ] && [ "$BATVAL" -le 50 ];then
        echo ""
      elif [ "$BATVAL" -gt 10 ] && [ "$BATVAL" -le 25 ];then
        echo ""
      fi
     else
      echo ""
    fi
}


if [[ "$1" == "--perc" ]]; then
	get_percentage
elif [[ "$1" == "--icon" ]]; then
	get_icon
fi

