#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
dunst &

# waybar
#$scripts/launch_waybar &


# wallpaper
$scripts/wallpaper $config/wallpapers/4.jpg &
$scripts/tools/dynamic &

# other
dbus-update-activation-environment --systemd --all WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

eww -c ~/.config/eww/bar/ open bar
kime &
udiskie & 
systemctl --user start hypridle hyprpolkitagent
mpd

